-- Delete application tables

BEGIN;

DROP TABLE IF EXISTS Note;
DROP TABLE IF EXISTS Lecture_Student;
DROP TABLE IF EXISTS Lecture;
DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS [Group];
DROP TABLE IF EXISTS Lecturer;
DROP TABLE IF EXISTS Discipline;
DROP TABLE IF EXISTS Schedule;

COMMIT;